Bootstrap: docker
From: alpine:edge

%labels
    AUTHOR icaoberg
    EMAIL icaoberg@psc.edu
    WEBSITE http://www.andrew.cmu.edu/~icaoberg
    VERSION 1.6.0

%post
    apk add --update nodejs npm

####################################################################################
%appinstall chalk-animation
    npm install --global chalk-animation

%apphelp chalk-animation
    chalk-animation --help

%apprun chalk-animation
    chalk-animation "$@"
